spring.application.name=catalogo-service

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

service.client-id=${SERVICE_CLIENT_ID}
service.client-secret=${SERVICE_CLIENT_SECRET}
service.jwt-secret=${SERVICE_JWT_SECRET}
service.jwt-expiration=${SERVICE_JWT_EXPIRATION}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
