CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login       VARCHAR(255) NOT NULL,
    password    VARCHAR(255),
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    email       VARCHAR(255),
    image_url   VARCHAR(255),
    lang_key    VARCHAR(255),
    activated   BOOLEAN NOT NULL,

    CONSTRAINT uk_users_login UNIQUE (login),
    CONSTRAINT uk_users_email UNIQUE (email)
);
